export type EmotionContent = {
  id: string
  label: string
  mascotName: string
  accent: string // cor hex de destaque
  bg: string // tom claro de fundo
  /** descrição visual do mascote (usada para gerar a ilustração) */
  look: string
  intro: string
  body: string // onde a emoção mora no corpo
  story: string
  familyActivity: string
  parentTip: string
  exercise: string
}

export type EmotionModule = {
  id: string
  title: string
  description: string
  emotionIds: string[]
}

export const emotions: EmotionContent[] = [
  // ───────────────────────── Módulo 1 — Emoções essenciais
  {
    id: "alegria",
    label: "Alegria",
    mascotName: "Lumi",
    accent: "#f4b400",
    bg: "#fff6da",
    look: "a sunny round yellow star-creature with rosy cheeks and a huge happy smile, tiny arms raised",
    intro: "A alegria é aquela vontade de pular, sorrir e contar para todo mundo o que aconteceu de bom.",
    body: "Ela mora no peito quentinho e nas bochechas que sobem quando a gente ri.",
    story: "Lumi acordou e viu o sol entrando pela janela. Ela respirou fundo, sorriu e decidiu espalhar luz por onde passava.",
    familyActivity: "Façam juntos um 'pote da alegria': escrevam num papelzinho algo bom que aconteceu hoje e guardem no pote.",
    parentTip: "Comemore as pequenas conquistas do seu filho. A alegria compartilhada vira memória afetiva.",
    exercise: "Desenhe ou escreva uma coisa que deixou você muito feliz hoje.",
  },
  {
    id: "tristeza",
    label: "Tristeza",
    mascotName: "Nuvi",
    accent: "#5b8def",
    bg: "#e8f0ff",
    look: "a soft pale-blue raincloud creature with droopy sleepy eyes and a tiny gentle frown",
    intro: "A tristeza aparece quando perdemos algo, sentimos falta de alguém ou as coisas não saem como queríamos.",
    body: "Ela mora num aperto na garganta e nos olhos que ficam cheios de água.",
    story: "Nuvi ficou cinza quando o amigo foi embora. Mas descobriu que chorar um pouquinho ajuda a nuvem a ficar mais leve.",
    familyActivity: "Façam um abraço de 20 segundos. Depois, conversem sobre o que deixou a criança triste.",
    parentTip: "Não apresse a tristeza do seu filho. Validar o sentimento ensina que tudo bem não estar bem às vezes.",
    exercise: "Conte sobre uma vez em que você ficou triste e o que ajudou a melhorar.",
  },
  {
    id: "medo",
    label: "Medo",
    mascotName: "Tibo",
    accent: "#8b5cf6",
    bg: "#f1ebff",
    look: "a small purple cat-like creature with very big round eyes and ears slightly back, holding a tiny lantern",
    intro: "O medo é um aviso do corpo que diz 'cuidado!'. Ele tenta nos proteger do que parece perigoso.",
    body: "Ele mora na barriga que embrulha e no coração que bate mais rápido.",
    story: "Tibo tinha medo do escuro, até acender sua lanterninha e perceber que as sombras eram só os brinquedos dormindo.",
    familyActivity: "Acendam uma lanterna no escuro e deem nome engraçado para cada sombra do quarto.",
    parentTip: "Nunca ridicularize o medo da criança. Mostre que você está por perto e que ela está segura.",
    exercise: "Escreva um medo seu e uma coisa que te ajuda a ser corajoso.",
  },
  {
    id: "raiva",
    label: "Raiva",
    mascotName: "Foguinho",
    accent: "#ef4444",
    bg: "#ffe9e6",
    look: "a fiery red round dragon-baby with steam puffs from its head and little crossed arms",
    intro: "A raiva surge quando algo parece injusto ou quando não conseguimos o que queremos.",
    body: "Ela mora no calor que sobe pelo rosto e nas mãos que querem se fechar.",
    story: "Foguinho ficou vermelho de raiva, mas aprendeu a respirar fundo três vezes até a chama virar uma fogueira calminha.",
    familyActivity: "Ensine o 'respira-balão': inflar a barriga inspirando e soltar o ar bem devagar, três vezes.",
    parentTip: "Ajude a nomear a raiva em vez de punir a explosão. Sentir raiva é normal; o que importa é o que fazemos com ela.",
    exercise: "Escreva o que te deixa com raiva e o que você pode fazer para se acalmar.",
  },
  {
    id: "nojo",
    label: "Nojo",
    mascotName: "Greta",
    accent: "#84cc16",
    bg: "#f0fbdc",
    look: "a lime-green wrinkly-nosed little blob creature sticking its tongue out playfully",
    intro: "O nojo nos avisa quando algo pode não fazer bem, como um cheiro ruim ou comida estragada.",
    body: "Ele mora no nariz que se enruga e na boca que faz 'eca!'.",
    story: "Greta torcia o nariz para tudo novo, até experimentar com coragem e descobrir sabores que passou a amar.",
    familyActivity: "Brincadeira do 'prove sem medo': experimentem juntos um alimento novo e descrevam o sabor.",
    parentTip: "Respeite os limites, mas convide a criança a experimentar aos poucos, sem forçar.",
    exercise: "Desenhe a cara que você faz quando sente nojo de alguma coisa.",
  },
  {
    id: "surpresa",
    label: "Surpresa",
    mascotName: "Zazá",
    accent: "#22c1bd",
    bg: "#dff8f6",
    look: "a teal squirrel-like creature with a fluffy tail, eyes wide open and mouth in a surprised O",
    intro: "A surpresa é aquele susto gostoso (ou não) quando algo inesperado acontece.",
    body: "Ela mora nos olhos que se arregalam e no pulinho que o corpo dá.",
    story: "Zazá abriu uma caixa achando que estava vazia e — pum! — saiu uma borboleta. Que surpresa boa!",
    familyActivity: "Façam uma caixa-surpresa com um objeto dentro e adivinhem pelo tato o que é.",
    parentTip: "Use surpresas positivas para fortalecer a confiança e o vínculo com a criança.",
    exercise: "Conte sobre a maior surpresa que você já teve.",
  },

  // ───────────────────────── Módulo 2 — Bem-estar e alegria
  {
    id: "calma",
    label: "Calma",
    mascotName: "Sereno",
    accent: "#34c79a",
    bg: "#e2f8f0",
    look: "a calm mint-green turtle with a leaf-patterned shell and gently closed peaceful eyes",
    intro: "A calma é aquela sensação de paz, quando a respiração fica lenta e tudo parece mais leve.",
    body: "Ela mora na respiração tranquila e nos ombros que relaxam.",
    story: "Sereno, a tartaruga, ensinou os amigos a respirar devagar como quem cheira uma flor e apaga uma vela.",
    familyActivity: "Deitem de costas com um bichinho de pelúcia na barriga e observem ele subir e descer com a respiração.",
    parentTip: "Crie momentos de silêncio e calma no dia. Crianças aprendem a se regular vendo os adultos calmos.",
    exercise: "Escreva ou desenhe um lugar onde você se sente bem tranquilo.",
  },
  {
    id: "gratidao",
    label: "Gratidão",
    mascotName: "Lina",
    accent: "#f59e0b",
    bg: "#fff2d6",
    look: "a warm orange deer fawn with a tiny flower behind the ear and a soft thankful smile",
    intro: "A gratidão é o carinho que sentimos por algo bom que temos ou que alguém fez por nós.",
    body: "Ela mora no sorriso suave e no coração quentinho.",
    story: "Lina parava todo fim de tarde para agradecer: pela comida, pelos amigos e até pela chuva que regava as flores.",
    familyActivity: "Antes de dormir, cada um diz três coisas pelas quais foi grato hoje.",
    parentTip: "Praticar gratidão em família aumenta o bem-estar de todos e ensina a valorizar o que se tem.",
    exercise: "Escreva três coisas pelas quais você é grato hoje.",
  },
  {
    id: "esperanca",
    label: "Esperança",
    mascotName: "Aurora",
    accent: "#38bdf8",
    bg: "#e0f5ff",
    look: "a light-blue bird with a tiny sunrise glow on its chest and hopeful upward gaze",
    intro: "A esperança é acreditar que coisas boas podem acontecer, mesmo quando o dia está difícil.",
    body: "Ela mora no olhar que mira o futuro e no peito que respira aliviado.",
    story: "Aurora cantava ao amanhecer, lembrando a todos que depois da noite mais escura sempre chega um novo dia.",
    familyActivity: "Façam um 'mural dos sonhos' com desenhos do que vocês esperam alcançar.",
    parentTip: "Ajude a criança a enxergar possibilidades diante de frustrações. Esperança se ensina pelo exemplo.",
    exercise: "Escreva algo bom que você espera que aconteça.",
  },
  {
    id: "entusiasmo",
    label: "Entusiasmo",
    mascotName: "Pim",
    accent: "#fb7185",
    bg: "#ffe7ec",
    look: "an energetic coral-pink rabbit mid-jump with sparkly eyes and big floppy ears flying up",
    intro: "O entusiasmo é aquela energia animada de quem mal pode esperar para começar algo.",
    body: "Ele mora nas pernas que querem correr e no sorriso que não cabe no rosto.",
    story: "Pim acordava pulando, animado com cada novidade do dia, contagiando todos com sua energia.",
    familyActivity: "Escolham juntos uma atividade nova para fazer no fim de semana e planejem com empolgação.",
    parentTip: "Valorize o entusiasmo do seu filho por novos interesses, mesmo que mudem com frequência.",
    exercise: "Escreva uma coisa que te deixa super animado.",
  },
  {
    id: "contentamento",
    label: "Contentamento",
    mascotName: "Bolota",
    accent: "#a3b18a",
    bg: "#eef2e2",
    look: "a chubby olive-green hedgehog curled up cozily with a content little smile",
    intro: "O contentamento é a alegria mansa de estar satisfeito com o momento, sem precisar de mais nada.",
    body: "Ele mora no suspiro gostoso e no corpo aconchegado.",
    story: "Bolota se enroscava na poltrona depois de brincar e pensava: 'que dia bom, está tudo certo assim'.",
    familyActivity: "Criem um 'cantinho do aconchego' com almofadas e fiquem ali juntos, sem pressa.",
    parentTip: "Mostre que felicidade também é apreciar o simples, sem sempre querer algo novo.",
    exercise: "Descreva um momento simples que te deixou contente.",
  },
  {
    id: "serenidade",
    label: "Serenidade",
    mascotName: "Lua",
    accent: "#818cf8",
    bg: "#eaecff",
    look: "a gentle indigo owl with half-closed serene eyes and tiny stars around its head",
    intro: "A serenidade é uma calma profunda, como o céu tranquilo de uma noite estrelada.",
    body: "Ela mora na mente quietinha e na respiração bem leve.",
    story: "Lua, a coruja, observava as estrelas em silêncio e sentia toda a floresta descansar junto com ela.",
    familyActivity: "Façam um minuto de silêncio juntos ouvindo só os sons ao redor.",
    parentTip: "Reserve momentos sem telas e sem pressa. A serenidade nasce do ritmo mais lento.",
    exercise: "Desenhe o que vem à sua mente quando você fica bem quietinho.",
  },
  {
    id: "otimismo",
    label: "Otimismo",
    mascotName: "Sol",
    accent: "#facc15",
    bg: "#fff7cc",
    look: "a bright golden lion cub with a mane shaped like sun rays and a confident grin",
    intro: "O otimismo é olhar para o lado bom das coisas e confiar que vai dar certo.",
    body: "Ele mora no queixo erguido e no sorriso confiante.",
    story: "Sol, o leãozinho, dizia: 'se errar, eu tento de novo!'. E assim transformava tropeços em aprendizados.",
    familyActivity: "Quando algo der errado, achem juntos uma coisa boa que ainda pode sair daquilo.",
    parentTip: "Ensine a reformular pensamentos negativos. Otimismo realista fortalece a resiliência.",
    exercise: "Escreva algo difícil que aconteceu e um lado bom que você encontrou.",
  },
  {
    id: "diversao",
    label: "Diversão",
    mascotName: "Tuck",
    accent: "#f97316",
    bg: "#ffead6",
    look: "an orange monkey-like creature laughing with arms wide open and a party hat",
    intro: "A diversão é a alegria de brincar, rir e se soltar sem se preocupar com nada.",
    body: "Ela mora na barriga que ri e nos pés que querem dançar.",
    story: "Tuck transformava qualquer tarefa em brincadeira e fazia todo mundo rir junto.",
    familyActivity: "Inventem uma dança maluca e dancem juntos por uma música inteira.",
    parentTip: "Brincar com seu filho fortalece o vínculo mais do que qualquer presente.",
    exercise: "Escreva a brincadeira mais divertida que você conhece.",
  },
  {
    id: "empolgacao",
    label: "Empolgação",
    mascotName: "Vivo",
    accent: "#ec4899",
    bg: "#ffe4f3",
    look: "a hot-pink frog mid-leap with stars in its eyes and a wide excited mouth",
    intro: "A empolgação é uma animação tão grande que parece que o corpo vai explodir de vontade.",
    body: "Ela mora no coração acelerado e nas mãos que batem palmas.",
    story: "Vivo ficou tão empolgado com o passeio que não conseguia parar de falar sobre ele.",
    familyActivity: "Façam uma contagem regressiva para algo esperado e marquem no calendário.",
    parentTip: "Acolha a empolgação e ajude a criança a esperar — a antecipação faz parte da alegria.",
    exercise: "Escreva algo que você está muito empolgado para fazer.",
  },
  {
    id: "satisfacao",
    label: "Satisfação",
    mascotName: "Dado",
    accent: "#10b981",
    bg: "#dcfaee",
    look: "a green beaver holding a tiny finished wooden toy with a proud satisfied smile",
    intro: "A satisfação é aquele 'consegui!' gostoso depois de terminar algo com capricho.",
    body: "Ela mora no peito que infla e no sorriso de dever cumprido.",
    story: "Dado construiu sua casinha pedacinho por pedacinho e sentiu uma satisfação enorme ao terminar.",
    familyActivity: "Terminem juntos uma pequena tarefa e celebrem com um 'toca aqui'.",
    parentTip: "Elogie o esforço e o processo, não só o resultado. Isso nutre a satisfação saudável.",
    exercise: "Escreva algo que você terminou e ficou orgulhoso.",
  },
  {
    id: "alivio",
    label: "Alívio",
    mascotName: "Sopro",
    accent: "#06b6d4",
    bg: "#dbf6fb",
    look: "a cyan whale-cloud creature exhaling a soft puff of air with relaxed closed eyes",
    intro: "O alívio é o respiro gostoso quando uma preocupação finalmente passa.",
    body: "Ele mora no suspiro fundo e nos ombros que descem.",
    story: "Sopro segurava a respiração com medo da prova, mas ao terminar soltou um 'ufa!' enorme de alívio.",
    familyActivity: "Ensine a soltar um 'ufa' bem longo depois de algo difícil terminar.",
    parentTip: "Reconheça o alívio do seu filho após desafios — ajuda a fechar o ciclo do estresse.",
    exercise: "Conte sobre uma vez em que você sentiu alívio.",
  },
  {
    id: "felicidade",
    label: "Felicidade",
    mascotName: "Fofo",
    accent: "#fbbf24",
    bg: "#fff4d2",
    look: "a fluffy golden cloud-bear with heart-shaped cheeks and a beaming radiant smile",
    intro: "A felicidade é um bem-estar grande que enche o coração e faz a gente brilhar.",
    body: "Ela mora no peito leve e no rosto que sorri sozinho.",
    story: "Fofo percebeu que era feliz quando estava perto de quem amava, fazendo o que gostava.",
    familyActivity: "Montem juntos um 'álbum da felicidade' com fotos ou desenhos de momentos felizes.",
    parentTip: "Ajude a criança a perceber que felicidade são muitos momentos pequenos somados.",
    exercise: "Desenhe o que é felicidade para você.",
  },

  // ───────────────────────── Módulo 3 — Medos e inseguranças
  {
    id: "ansiedade",
    label: "Ansiedade",
    mascotName: "Friso",
    accent: "#7c3aed",
    bg: "#efe8ff",
    look: "a violet ferret-like creature with a slightly tangled tail and worried wide eyes",
    intro: "A ansiedade é quando ficamos muito preocupados com algo que ainda nem aconteceu.",
    body: "Ela mora na barriga embrulhada e nos pensamentos acelerados.",
    story: "Friso ficava todo enrolado pensando no amanhã, até aprender a voltar para o agora respirando devagar.",
    familyActivity: "Façam o jogo do '5 sentidos': digam 5 coisas que veem, 4 que ouvem, 3 que tocam, 2 que cheiram e 1 que sentem.",
    parentTip: "Ajude a criança a focar no presente. Antecipar demais alimenta a ansiedade.",
    exercise: "Escreva uma preocupação sua e uma frase calminha para repetir.",
  },
  {
    id: "inseguranca",
    label: "Insegurança",
    mascotName: "Timi",
    accent: "#a78bfa",
    bg: "#f0ebff",
    look: "a lavender mouse peeking shyly from behind its own tail with uncertain eyes",
    intro: "A insegurança é a dúvida de 'será que eu consigo?' que aparece antes de tentar algo.",
    body: "Ela mora no passo que hesita e na voz que fica baixinha.",
    story: "Timi achava que não daria conta, mas deu um passinho de cada vez e percebeu que era capaz.",
    familyActivity: "Listem juntos coisas que a criança já aprendeu a fazer sozinha, mesmo achando difícil antes.",
    parentTip: "Relembre conquistas passadas do seu filho. Provas concretas vencem a insegurança.",
    exercise: "Escreva algo que você achava difícil e hoje consegue fazer.",
  },
  {
    id: "timidez",
    label: "Timidez",
    mascotName: "Concha",
    accent: "#f472b6",
    bg: "#ffe6f1",
    look: "a pink snail peeking half-out of its swirly shell with a shy little smile",
    intro: "A timidez é aquele receio de se mostrar ou falar perto de gente que a gente não conhece bem.",
    body: "Ela mora nas bochechas que coram e nos olhos que olham para o chão.",
    story: "Concha ficava dentro do casco perto de estranhos, mas saía devagarinho quando se sentia segura.",
    familyActivity: "Pratiquem cumprimentar pessoas com um 'oi' e um sorriso, começando pela família.",
    parentTip: "Não rotule a criança de 'tímida'. Dê tempo e segurança para ela se abrir no ritmo dela.",
    exercise: "Escreva uma situação em que você fica tímido.",
  },
  {
    id: "nervosismo",
    label: "Nervosismo",
    mascotName: "Trê",
    accent: "#8b5cf6",
    bg: "#efe9fe",
    look: "a purple grasshopper with slightly shaky legs and a nervous tiny smile",
    intro: "O nervosismo é o frio na barriga antes de um momento importante, como uma apresentação.",
    body: "Ele mora nas mãos suadas e no coração que dispara.",
    story: "Trê tremia antes de pular, mas respirava, contava até três e dava seu melhor salto.",
    familyActivity: "Façam um 'ensaio' do que deixa a criança nervosa, transformando em brincadeira.",
    parentTip: "Normalize o nervosismo: até adultos sentem. Ensaiar reduz o desconforto.",
    exercise: "Escreva algo que te deixa nervoso e como você se prepara.",
  },
  {
    id: "preocupacao",
    label: "Preocupação",
    mascotName: "Penso",
    accent: "#6366f1",
    bg: "#e8eaff",
    look: "an indigo elephant with a small thought-cloud over its head and a thoughtful frown",
    intro: "A preocupação é quando ficamos pensando muito em um problema, tentando resolver tudo na cabeça.",
    body: "Ela mora na testa franzida e nos pensamentos que rodam.",
    story: "Penso carregava preocupações pesadas até desenhá-las num papel e perceber que ficavam menores.",
    familyActivity: "Criem uma 'caixa das preocupações': escrevam o que preocupa e guardem para conversar depois.",
    parentTip: "Reserve um 'horário da preocupação' curto para conversar, evitando que ela domine o dia.",
    exercise: "Escreva uma preocupação e quem pode te ajudar com ela.",
  },
  {
    id: "receio",
    label: "Receio",
    mascotName: "Cauto",
    accent: "#0ea5e9",
    bg: "#e2f4fe",
    look: "a sky-blue tortoise poking its head out carefully, testing the ground with one foot",
    intro: "O receio é um medinho leve que faz a gente ir com cuidado antes de algo novo.",
    body: "Ele mora no passo devagar e no olhar atento.",
    story: "Cauto testava a água com a pata antes de entrar, e isso o mantinha seguro sem deixar de tentar.",
    familyActivity: "Antes de uma novidade, listem juntos o que pode dar certo para reduzir o receio.",
    parentTip: "Receio saudável protege. Ajude a diferenciar cuidado de medo que paralisa.",
    exercise: "Escreva algo novo que você gostaria de tentar com cuidado.",
  },
  {
    id: "susto",
    label: "Susto",
    mascotName: "Pula",
    accent: "#f43f5e",
    bg: "#ffe4e8",
    look: "a red-orange kangaroo-like creature jumping with a startled wide-eyed expression",
    intro: "O susto é aquela reação rápida quando algo inesperado nos pega de surpresa.",
    body: "Ele mora no pulo do corpo e no coração que dispara num segundo.",
    story: "Pula levou um susto com o trovão, mas logo riu ao perceber que era só a chuva chegando.",
    familyActivity: "Brinquem de 'achou!' de leve e riam juntos dos sustinhos bobos.",
    parentTip: "Após um susto, acolha com calma e explique o que aconteceu para tranquilizar.",
    exercise: "Conte sobre um susto que depois virou motivo de riso.",
  },
  {
    id: "aflicao",
    label: "Aflição",
    mascotName: "Nó",
    accent: "#9333ea",
    bg: "#f3e8ff",
    look: "a purple octopus-baby with tangled little arms and an uneasy expression",
    intro: "A aflição é uma inquietação grande, como se a gente não conseguisse ficar parado.",
    body: "Ela mora no peito apertado e nas mãos que não param.",
    story: "Nó ficava todo embolado de aflição, até desembaraçar um bracinho de cada vez, respirando.",
    familyActivity: "Façam um alongamento lento, esticando os braços e soltando o ar, para desfazer o 'nó'.",
    parentTip: "Ajude a criança a nomear a aflição e a desacelerar com o corpo antes de resolver.",
    exercise: "Desenhe como é a sua aflição e o que ajuda a desfazê-la.",
  },
  {
    id: "vergonha",
    label: "Vergonha",
    mascotName: "Rubi",
    accent: "#e11d48",
    bg: "#ffe4e9",
    look: "a rosy-red panda covering its face shyly with its paws, cheeks glowing",
    intro: "A vergonha aparece quando achamos que fizemos algo errado ou que estão todos nos olhando.",
    body: "Ela mora nas bochechas quentes e na vontade de se esconder.",
    story: "Rubi cobriu o rosto após tropeçar, mas percebeu que todos erram e que ninguém riu por maldade.",
    familyActivity: "Compartilhem cada um uma 'mancada' boba que já fizeram e riam juntos com carinho.",
    parentTip: "Mostre que errar é humano. Reduzir a vergonha fortalece a autoestima.",
    exercise: "Escreva uma vez que sentiu vergonha e o que aprendeu.",
  },
  {
    id: "constrangimento",
    label: "Constrangimento",
    mascotName: "Tomá",
    accent: "#fb7185",
    bg: "#ffe8ec",
    look: "a salmon-pink flamingo with one wing over its beak, looking a bit embarrassed",
    intro: "O constrangimento é um desconforto quando ficamos sem graça diante dos outros.",
    body: "Ele mora no sorriso sem jeito e no corpo que se encolhe um pouco.",
    story: "Tomá errou o nome de um amigo e ficou sem graça, mas pediu desculpa e tudo ficou bem.",
    familyActivity: "Ensaiar frases simpáticas para sair de saias-justas, como 'ops, me confundi!'.",
    parentTip: "Ajude a criança a perceber que momentos sem graça passam rápido e não a definem.",
    exercise: "Escreva uma situação sem graça e como você reagiria com leveza.",
  },

  // ───────────────────────── Módulo 4 — Raiva e frustração
  {
    id: "frustracao",
    label: "Frustração",
    mascotName: "Grru",
    accent: "#f97316",
    bg: "#ffe8d6",
    look: "an orange bulldog-like creature with a pouty face and arms crossed in a huff",
    intro: "A frustração vem quando tentamos algo e não conseguimos do jeito que queríamos.",
    body: "Ela mora no bufo e nos ombros que caem.",
    story: "Grru não conseguia montar o quebra-cabeça e quase desistiu, mas tentou de novo com calma e conseguiu.",
    familyActivity: "Quando algo der errado, digam juntos: 'ainda não consegui, mas vou tentar de novo'.",
    parentTip: "Resista a resolver tudo pela criança. Tolerar a frustração constrói resiliência.",
    exercise: "Escreva algo que te frustrou e o que você pode tentar de novo.",
  },
  {
    id: "irritacao",
    label: "Irritação",
    mascotName: "Zune",
    accent: "#eab308",
    bg: "#fdf3cf",
    look: "a yellow wasp-like creature with a small frown and tiny buzzing wings",
    intro: "A irritação é uma raiva pequena que incomoda, como um mosquito zumbindo no ouvido.",
    body: "Ela mora na sobrancelha franzida e na paciência curtinha.",
    story: "Zune zumbia de irritação com o barulho, até afastar-se um pouco e encontrar um cantinho quieto.",
    familyActivity: "Criem um sinal de mão para avisar 'estou irritado, preciso de um espaço'.",
    parentTip: "Ensine a criança a pedir uma pausa antes que a irritação vire explosão.",
    exercise: "Escreva o que te irrita e o que ajuda a aliviar.",
  },
  {
    id: "ciume",
    label: "Ciúme",
    mascotName: "Mio",
    accent: "#14b8a6",
    bg: "#d8f7f1",
    look: "a teal cat hugging a small heart tightly, glancing sideways with a worried look",
    intro: "O ciúme aparece quando temos medo de perder a atenção de quem amamos para outra pessoa.",
    body: "Ele mora no aperto no peito e no olhar atento ao outro.",
    story: "Mio sentiu ciúme do novo amigo do irmão, mas descobriu que cabia carinho para todos.",
    familyActivity: "Reservem um tempo só para a criança, mostrando que o amor não diminui ao ser dividido.",
    parentTip: "Acolha o ciúme sem julgar. Garanta atenção exclusiva para reduzir a insegurança.",
    exercise: "Escreva uma vez que sentiu ciúme e como se sentiu melhor.",
  },
  {
    id: "inveja",
    label: "Inveja",
    mascotName: "Cobi",
    accent: "#16a34a",
    bg: "#dcf6e3",
    look: "a green chameleon looking at a shiny toy with longing, its color shifting to green",
    intro: "A inveja é querer muito algo que o outro tem. Ela pode virar motivação se a gente conversar sobre ela.",
    body: "Ela mora no olhar comparativo e no 'eu também queria'.",
    story: "Cobi queria o brinquedo do amigo, mas percebeu que tinha coisas legais para compartilhar também.",
    familyActivity: "Listem juntos coisas boas que a criança já tem e do que ela se orgulha.",
    parentTip: "Transforme inveja em metas saudáveis, sem comparação que diminui o outro.",
    exercise: "Escreva algo que você admira no outro e uma qualidade sua.",
  },
  {
    id: "impaciencia",
    label: "Impaciência",
    mascotName: "Tique",
    accent: "#f59e0b",
    bg: "#fff0d2",
    look: "an amber rabbit tapping its foot quickly next to a tiny clock, eyebrows raised",
    intro: "A impaciência é a dificuldade de esperar quando queremos algo agora mesmo.",
    body: "Ela mora no pé que bate no chão e no suspiro impaciente.",
    story: "Tique não queria esperar o bolo assar, mas brincou enquanto isso e o tempo passou voando.",
    familyActivity: "Usem um cronômetro de areia e brinquem de esperar até a areia terminar.",
    parentTip: "Ensine estratégias para a espera. Paciência é uma habilidade que se treina.",
    exercise: "Escreva algo que é difícil esperar e o que ajuda a passar o tempo.",
  },
  {
    id: "teimosia",
    label: "Teimosia",
    mascotName: "Buru",
    accent: "#d97706",
    bg: "#ffeccc",
    look: "a stubborn brown little bull with planted hooves and a determined pout",
    intro: "A teimosia é insistir no nosso jeito mesmo quando alguém sugere outro caminho.",
    body: "Ela mora nos braços cruzados e no 'não!' firme.",
    story: "Buru não queria mudar de ideia, até ouvir o amigo e perceber que havia um jeito ainda melhor.",
    familyActivity: "Brinquem de 'trocar de lugar': cada um defende a ideia do outro por um minuto.",
    parentTip: "Ofereça escolhas dentro de limites. Isso reduz a teimosia e dá senso de controle.",
    exercise: "Escreva uma vez em que você mudou de ideia e foi bom.",
  },
  {
    id: "birra",
    label: "Birra",
    mascotName: "Tufa",
    accent: "#ef4444",
    bg: "#ffe5e2",
    look: "a small red storm-cloud creature with a grumpy face and tiny stomping feet",
    intro: "A birra é uma explosão de raiva e choro quando os sentimentos ficam grandes demais.",
    body: "Ela mora no corpo todo, que se debate e chora alto.",
    story: "Tufa virou uma tempestade de birra, mas no colo seguro foi se acalmando como nuvem que passa.",
    familyActivity: "Após a birra passar, conversem com calma sobre o que a criança estava sentindo.",
    parentTip: "Mantenha-se calmo durante a birra. A criança precisa do seu equilíbrio para se regular.",
    exercise: "Desenhe sua birra como uma tempestade e o sol que vem depois.",
  },
  {
    id: "indignacao",
    label: "Indignação",
    mascotName: "Justo",
    accent: "#dc2626",
    bg: "#ffe3e0",
    look: "a red rooster standing tall with chest out, looking firm and righteous",
    intro: "A indignação é a raiva que sentimos diante de algo injusto.",
    body: "Ela mora no peito estufado e na voz firme que quer falar.",
    story: "Justo viu um amigo sendo excluído e usou sua voz com firmeza para defender o que era justo.",
    familyActivity: "Conversem sobre o que é justo e injusto usando situações do dia a dia.",
    parentTip: "Valorize o senso de justiça do seu filho e ensine a expressá-lo com respeito.",
    exercise: "Escreva algo que você acha injusto e como mudaria isso.",
  },
  {
    id: "rancor",
    label: "Rancor",
    mascotName: "Espin",
    accent: "#b45309",
    bg: "#f3e3da",
    look: "a brown porcupine with raised quills holding a tiny grudge-rock, frowning",
    intro: "O rancor é uma mágoa guardada que pesa e machuca quem carrega.",
    body: "Ele mora no aperto que não passa e nos espinhos arrepiados.",
    story: "Espin guardava pedrinhas de mágoa até ficar pesado demais; ao soltá-las, sentiu-se leve de novo.",
    familyActivity: "Escrevam uma mágoa num papel e, juntos, amassem e joguem fora como quem solta o peso.",
    parentTip: "Ajude a criança a falar sobre mágoas. Guardar rancor faz mal a ela mesma.",
    exercise: "Escreva uma mágoa que você gostaria de soltar.",
  },
  {
    id: "aborrecimento",
    label: "Aborrecimento",
    mascotName: "Mufo",
    accent: "#a16207",
    bg: "#f7eccb",
    look: "a mustard-colored sloth slouching with a bored, unimpressed expression",
    intro: "O aborrecimento é o tédio chato de quando nada parece interessante.",
    body: "Ele mora no suspiro entediado e no corpo molenga.",
    story: "Mufo achava tudo sem graça, até usar a imaginação e transformar a tarde num grande jogo.",
    familyActivity: "Façam uma 'lista anti-tédio' com ideias para quando bater o aborrecimento.",
    parentTip: "Tédio também é saudável: estimula a criatividade. Não preencha todos os espaços.",
    exercise: "Escreva o que você pode fazer quando estiver entediado.",
  },

  // ───────────────────────── Módulo 5 — Conexão e afeto
  {
    id: "carinho",
    label: "Carinho",
    mascotName: "Mel",
    accent: "#ec4899",
    bg: "#ffe4f1",
    look: "a pink bunny hugging a small red heart with a tender warm smile",
    intro: "O carinho é o jeito gentil de demonstrar que gostamos de alguém.",
    body: "Ele mora no abraço quentinho e no toque suave.",
    story: "Mel adorava distribuir abraços e percebia que o carinho voltava sempre em dobro.",
    familyActivity: "Façam uma 'chuva de carinho': cada um diz algo gentil sobre o outro.",
    parentTip: "Demonstre afeto físico e verbal todos os dias. Carinho é alimento emocional.",
    exercise: "Escreva uma forma de demonstrar carinho por alguém que você ama.",
  },
  {
    id: "amor",
    label: "Amor",
    mascotName: "Coro",
    accent: "#e11d48",
    bg: "#ffe2e8",
    look: "a red heart-shaped creature with tiny wings and a glowing gentle face",
    intro: "O amor é o sentimento mais forte de querer bem, cuidar e estar perto de quem é especial.",
    body: "Ele mora no coração inteiro e no olhar que se ilumina.",
    story: "Coro batia mais forte perto da família e entendia que amar é cuidar todos os dias.",
    familyActivity: "Façam um 'mural do amor' com fotos e desenhos de quem vocês amam.",
    parentTip: "Diga 'eu te amo' com frequência. Crianças amadas se tornam adultos seguros.",
    exercise: "Escreva para quem você sente muito amor e por quê.",
  },
  {
    id: "amizade",
    label: "Amizade",
    mascotName: "Duo",
    accent: "#f59e0b",
    bg: "#fff1d4",
    look: "two small yellow bird friends side by side sharing one big smile",
    intro: "A amizade é o carinho que sentimos por quem brinca, ajuda e compartilha conosco.",
    body: "Ela mora na alegria de estar junto e na mão que se estende.",
    story: "Duo eram dois passarinhos inseparáveis que aprenderam que amigo de verdade também sabe perdoar.",
    familyActivity: "Desenhem juntos um cartão para um amigo querido.",
    parentTip: "Ensine sobre dar e receber na amizade, incluindo combinar e perdoar.",
    exercise: "Escreva o que faz de alguém um bom amigo.",
  },
  {
    id: "empatia",
    label: "Empatia",
    mascotName: "Sente",
    accent: "#0d9488",
    bg: "#d6f5f0",
    look: "a teal deer gently touching another creature's shoulder with a caring look",
    intro: "A empatia é sentir junto, tentando entender o que o outro está passando.",
    body: "Ela mora no coração que se conecta e nos ouvidos que escutam.",
    story: "Sente percebeu que o amigo estava triste e sentou ao lado dele só para fazer companhia.",
    familyActivity: "Adivinhem como o personagem de um livro se sente e por quê.",
    parentTip: "Modele empatia nomeando sentimentos dos outros no dia a dia.",
    exercise: "Escreva como você ajudaria um amigo que está triste.",
  },
  {
    id: "compaixao",
    label: "Compaixão",
    mascotName: "Doa",
    accent: "#0891b2",
    bg: "#d9f3fb",
    look: "a cyan dove offering a tiny flower with a kind, gentle expression",
    intro: "A compaixão é a vontade de ajudar quem está sofrendo.",
    body: "Ela mora no impulso de cuidar e nas mãos que acolhem.",
    story: "Doa viu um filhote perdido e o ajudou a encontrar o caminho de casa.",
    familyActivity: "Façam uma boa ação juntos, como ajudar um vizinho ou doar um brinquedo.",
    parentTip: "Pratique gestos de bondade em família. A compaixão se aprende fazendo.",
    exercise: "Escreva uma forma de ajudar alguém que precisa.",
  },
  {
    id: "ternura",
    label: "Ternura",
    mascotName: "Plumi",
    accent: "#f9a8d4",
    bg: "#ffe9f4",
    look: "a soft pastel-pink lamb nuzzling gently with sleepy tender eyes",
    intro: "A ternura é um carinho suave e delicado, como afagar algo muito querido.",
    body: "Ela mora no toque leve e no olhar docinho.",
    story: "Plumi cuidava das plantinhas com tanta ternura que todas floresciam felizes.",
    familyActivity: "Cuidem juntos de uma plantinha ou bichinho com gestos delicados.",
    parentTip: "Momentos de ternura, como ninar e afagar, regulam as emoções da criança.",
    exercise: "Desenhe algo que você trata com muita ternura.",
  },
  {
    id: "saudade",
    label: "Saudade",
    mascotName: "Longe",
    accent: "#6366f1",
    bg: "#e9eaff",
    look: "an indigo bird looking at a small framed photo with a wistful gentle smile",
    intro: "A saudade é a falta gostosa-dolorida de quem amamos e está longe.",
    body: "Ela mora no peito apertado e na lembrança que sorri.",
    story: "Longe sentia saudade da avó, então desenhava cartas e guardava as boas lembranças no coração.",
    familyActivity: "Façam uma ligação ou um desenho para alguém de quem sentem saudade.",
    parentTip: "Valide a saudade da criança e ajude a manter o vínculo com quem está distante.",
    exercise: "Escreva de quem você sente saudade e uma lembrança boa dessa pessoa.",
  },
  {
    id: "pertencimento",
    label: "Pertencimento",
    mascotName: "Nido",
    accent: "#16a34a",
    bg: "#dcf6e1",
    look: "a green bird snug in a cozy nest with family, feeling safe and belonging",
    intro: "O pertencimento é a sensação boa de fazer parte de um grupo, de ter o seu lugar.",
    body: "Ele mora na segurança do colo e no 'aqui é o meu lugar'.",
    story: "Nido se sentia em casa no ninho cheio de família, sabendo que sempre teria um cantinho ali.",
    familyActivity: "Criem um símbolo ou lema só da família de vocês.",
    parentTip: "Reforce que a criança é parte importante da família, com seu papel e valor.",
    exercise: "Escreva um lugar ou grupo onde você se sente parte.",
  },
  {
    id: "confianca",
    label: "Confiança",
    mascotName: "Firme",
    accent: "#2563eb",
    bg: "#e2ecff",
    look: "a blue strong-armed bear standing steady with a reassuring confident smile",
    intro: "A confiança é acreditar em si e nas pessoas que cuidam da gente.",
    body: "Ela mora no peito firme e no passo seguro.",
    story: "Firme aprendeu a confiar quando percebeu que sempre havia alguém para segurar sua mão.",
    familyActivity: "Brinquem do 'cair confiando': a criança se inclina e você a segura com cuidado.",
    parentTip: "Cumpra o que promete. Confiança se constrói na consistência do dia a dia.",
    exercise: "Escreva em quem você confia e por quê.",
  },
  {
    id: "admiracao",
    label: "Admiração",
    mascotName: "Brilha",
    accent: "#8b5cf6",
    bg: "#efe9ff",
    look: "a purple peacock with shimmering feathers and starry admiring eyes",
    intro: "A admiração é olhar para alguém ou algo e pensar 'que incrível!'.",
    body: "Ela mora nos olhos brilhantes e no sorriso encantado.",
    story: "Brilha admirava as estrelas e os heróis, e sonhava em um dia também inspirar alguém.",
    familyActivity: "Contem quem vocês admiram e por quais qualidades.",
    parentTip: "Ajude a criança a admirar atitudes e caráter, não só aparências.",
    exercise: "Escreva quem você admira e o que aprende com essa pessoa.",
  },
  {
    id: "afeto",
    label: "Afeto",
    mascotName: "Coala",
    accent: "#fb7185",
    bg: "#ffe6eb",
    look: "a coral koala hugging warmly with closed happy eyes and a soft smile",
    intro: "O afeto é o carinho constante que aquece as relações do dia a dia.",
    body: "Ele mora no abraço de bom dia e no beijo de boa noite.",
    story: "Coala adorava os pequenos gestos de afeto que faziam o dia de todos ficar melhor.",
    familyActivity: "Combinem um gesto de afeto especial entre vocês, como um aperto de mão secreto.",
    parentTip: "Pequenos gestos diários de afeto criam segurança emocional duradoura.",
    exercise: "Escreva um gesto de afeto que você gosta de receber.",
  },
  {
    id: "cuidado",
    label: "Cuidado",
    mascotName: "Zelo",
    accent: "#0d9488",
    bg: "#d7f4ef",
    look: "a teal beaver tucking a tiny creature into a leaf blanket with care",
    intro: "O cuidado é a atenção carinhosa de proteger e ajudar quem amamos.",
    body: "Ele mora nas mãos atentas e no olhar protetor.",
    story: "Zelo cuidava de todos no rio, lembrando cada um de se proteger e descansar.",
    familyActivity: "Cada um cuida de uma tarefa da casa hoje, mostrando que cuidar é demonstrar amor.",
    parentTip: "Dê pequenas responsabilidades de cuidado. Isso desenvolve empatia e autonomia.",
    exercise: "Escreva como você cuida de alguém ou de algo.",
  },

  // ───────────────────────── Módulo 6 — Crescimento e superação
  {
    id: "coragem",
    label: "Coragem",
    mascotName: "Viko",
    accent: "#f97316",
    bg: "#ffe9d5",
    look: "an orange fox-lion cub wearing a small cape, standing brave with a determined smile",
    intro: "A coragem é seguir em frente mesmo sentindo medo, fazendo o que é importante.",
    body: "Ela mora no peito firme e no passo decidido.",
    story: "Viko sentia medo, mas vestia sua capa e dava o primeiro passo — e o medo ia ficando pequeno.",
    familyActivity: "Escolham um pequeno desafio do dia e enfrentem juntos, comemorando a coragem.",
    parentTip: "Elogie a coragem de tentar, não só o sucesso. Coragem cresce com apoio.",
    exercise: "Escreva algo corajoso que você fez ou quer fazer.",
  },
  {
    id: "curiosidade",
    label: "Curiosidade",
    mascotName: "Pipo",
    accent: "#8b5cf6",
    bg: "#f0eaff",
    look: "a purple owl-fox with a tiny magnifying glass and bright inquisitive eyes",
    intro: "A curiosidade é a vontade gostosa de descobrir, perguntar e explorar o mundo.",
    body: "Ela mora nos olhos atentos e no 'por quê?' que não para.",
    story: "Pipo vivia perguntando 'por quê?' e cada resposta abria uma porta nova de descobertas.",
    familyActivity: "Escolham uma pergunta curiosa e pesquisem juntos a resposta.",
    parentTip: "Acolha as perguntas do seu filho. Curiosidade é o motor do aprendizado.",
    exercise: "Escreva algo que você tem muita curiosidade de saber.",
  },
  {
    id: "orgulho",
    label: "Orgulho",
    mascotName: "Plumo",
    accent: "#f59e0b",
    bg: "#fff1d3",
    look: "a golden peacock proudly showing its tail feathers with a confident smile",
    intro: "O orgulho saudável é a alegria de reconhecer o próprio esforço e conquistas.",
    body: "Ele mora no peito estufado e no sorriso de 'eu consegui'.",
    story: "Plumo abria as penas com orgulho a cada coisa nova que aprendia a fazer sozinho.",
    familyActivity: "Façam um 'quadro de conquistas' e adicionem algo novo a cada semana.",
    parentTip: "Ensine orgulho do esforço, não da superioridade. Celebre o progresso.",
    exercise: "Escreva algo que você fez e que te deixou orgulhoso.",
  },
  {
    id: "determinacao",
    label: "Determinação",
    mascotName: "Rocha",
    accent: "#475569",
    bg: "#e9eef3",
    look: "a sturdy gray rhino-baby marching forward with a focused determined face",
    intro: "A determinação é a força de continuar mesmo quando o caminho fica difícil.",
    body: "Ela mora no queixo firme e nos pés que não param.",
    story: "Rocha queria chegar ao topo da colina e, passo a passo, sem desistir, conseguiu.",
    familyActivity: "Definam uma pequena meta e marquem cada passo até alcançá-la.",
    parentTip: "Divida grandes objetivos em pequenos passos. Determinação se sustenta com conquistas visíveis.",
    exercise: "Escreva uma meta sua e o primeiro passo para alcançá-la.",
  },
  {
    id: "paciencia",
    label: "Paciência",
    mascotName: "Vaga",
    accent: "#0ea5e9",
    bg: "#e1f4fe",
    look: "a sky-blue snail smiling calmly while moving slowly along a leaf",
    intro: "A paciência é saber esperar com calma, confiando que cada coisa tem seu tempo.",
    body: "Ela mora na respiração tranquila e na espera serena.",
    story: "Vaga não tinha pressa: regava a sementinha todo dia e esperou até virar uma flor linda.",
    familyActivity: "Plantem uma sementinha e acompanhem juntos, com paciência, o crescimento.",
    parentTip: "Modele paciência nas esperas. Crianças aprendem o ritmo calmo observando você.",
    exercise: "Escreva algo que valeu a pena esperar.",
  },
  {
    id: "persistencia",
    label: "Persistência",
    mascotName: "Teço",
    accent: "#7c3aed",
    bg: "#efe8ff",
    look: "a violet spider weaving a web again with a patient persistent smile",
    intro: "A persistência é tentar de novo e de novo, sem desistir do que é importante.",
    body: "Ela mora nas mãos que recomeçam e na vontade que não acaba.",
    story: "Teço refazia a teia toda vez que o vento desmanchava, até ela ficar firme e bonita.",
    familyActivity: "Escolham algo difícil e tentem juntos três vezes, comemorando cada tentativa.",
    parentTip: "Valorize a tentativa. 'Errar e tentar de novo' é a base do aprendizado.",
    exercise: "Escreva algo que você conseguiu depois de muito tentar.",
  },
  {
    id: "criatividade",
    label: "Criatividade",
    mascotName: "Inventa",
    accent: "#ec4899",
    bg: "#ffe4f2",
    look: "a magenta fox with a paint-splattered tail and a lightbulb sparkle above its head",
    intro: "A criatividade é a magia de inventar, imaginar e criar coisas novas do seu jeito.",
    body: "Ela mora nas mãos que criam e na mente cheia de ideias.",
    story: "Inventa transformava caixas em foguetes e cobertores em castelos, criando mundos inteiros.",
    familyActivity: "Criem algo com materiais reciclados, sem regras, só imaginação.",
    parentTip: "Ofereça materiais livres e elogie ideias originais, não só o resultado bonito.",
    exercise: "Desenhe ou descreva uma invenção sua.",
  },
  {
    id: "imaginacao",
    label: "Imaginação",
    mascotName: "Sonha",
    accent: "#a855f7",
    bg: "#f3e8ff",
    look: "a lavender winged-unicorn foal with dreamy eyes and floating little clouds",
    intro: "A imaginação é a capacidade de criar histórias e mundos só com o pensamento.",
    body: "Ela mora nos olhos que viajam e na mente que voa.",
    story: "Sonha fechava os olhos e viajava para reinos mágicos cheios de aventuras.",
    familyActivity: "Inventem uma história juntos, cada um acrescentando uma parte.",
    parentTip: "Brincadeiras de faz de conta desenvolvem linguagem, empatia e resolução de problemas.",
    exercise: "Escreva o começo de uma história mágica que você imaginar.",
  },
  {
    id: "concentracao",
    label: "Concentração",
    mascotName: "Foca",
    accent: "#2563eb",
    bg: "#e3ecff",
    look: "a blue cat staring intently at a single ball of yarn with focused eyes",
    intro: "A concentração é prestar bastante atenção em uma coisa de cada vez.",
    body: "Ela mora no olhar fixo e na mente quietinha.",
    story: "Foca aprendeu que, fazendo uma coisa de cada vez, terminava tudo bem mais rápido.",
    familyActivity: "Façam um quebra-cabeça em silêncio, focando só nele por alguns minutos.",
    parentTip: "Reduza distrações e telas durante tarefas. A concentração se treina aos poucos.",
    exercise: "Escreva uma atividade em que você consegue se concentrar bastante.",
  },
  {
    id: "responsabilidade",
    label: "Responsabilidade",
    mascotName: "Guto",
    accent: "#0d9488",
    bg: "#d8f4ef",
    look: "a teal dog wearing a tiny backpack, organizing small tasks with a proud look",
    intro: "A responsabilidade é cuidar das nossas tarefas e cumprir o que combinamos.",
    body: "Ela mora no compromisso cumprido e no orgulho de dar conta.",
    story: "Guto cuidava de suas tarefas com capricho e sentia-se cada dia mais crescido.",
    familyActivity: "Escolham uma pequena tarefa para a criança cuidar sozinha esta semana.",
    parentTip: "Dê responsabilidades adequadas à idade. Elas constroem autonomia e autoestima.",
    exercise: "Escreva uma tarefa pela qual você é responsável.",
  },
  {
    id: "generosidade",
    label: "Generosidade",
    mascotName: "Parti",
    accent: "#16a34a",
    bg: "#dcf6e2",
    look: "a green squirrel sharing nuts from its paws with a warm giving smile",
    intro: "A generosidade é a alegria de compartilhar e dar sem esperar nada em troca.",
    body: "Ela mora nas mãos que dividem e no coração que se abre.",
    story: "Parti dividia suas nozes com todos e descobria que a alegria também crescia ao ser repartida.",
    familyActivity: "Separem juntos brinquedos ou roupas para doar a quem precisa.",
    parentTip: "Pratique a generosidade em família. Compartilhar se aprende vendo e fazendo.",
    exercise: "Escreva algo que você pode compartilhar com alguém.",
  },
  {
    id: "honestidade",
    label: "Honestidade",
    mascotName: "Vero",
    accent: "#0891b2",
    bg: "#d9f2fb",
    look: "a cyan dog with an open honest face holding a small badge",
    intro: "A honestidade é falar a verdade e agir com sinceridade, mesmo quando é difícil.",
    body: "Ela mora na voz firme e no olhar limpo.",
    story: "Vero contou a verdade mesmo com medo, e percebeu que a confiança ficou ainda mais forte.",
    familyActivity: "Conversem sobre uma vez em que falar a verdade foi difícil, mas importante.",
    parentTip: "Reaja com calma à verdade dita. Punir a sinceridade ensina a esconder.",
    exercise: "Escreva por que falar a verdade é importante para você.",
  },
  {
    id: "respeito",
    label: "Respeito",
    mascotName: "Cordi",
    accent: "#4f46e5",
    bg: "#e8e9ff",
    look: "an indigo elephant bowing politely with a kind respectful expression",
    intro: "O respeito é tratar os outros e a si mesmo com cuidado e consideração.",
    body: "Ele mora nas palavras gentis e na escuta atenta.",
    story: "Cordi ouvia todos com atenção e esperava sua vez de falar, e por isso era muito querido.",
    familyActivity: "Pratiquem ouvir até o fim sem interromper, revezando quem fala.",
    parentTip: "Respeite a criança para que ela aprenda a respeitar. O exemplo é o melhor ensino.",
    exercise: "Escreva uma forma de demonstrar respeito por alguém.",
  },
  {
    id: "gentileza",
    label: "Gentileza",
    mascotName: "Suave",
    accent: "#f472b6",
    bg: "#ffe7f2",
    look: "a soft-pink rabbit offering a small flower with a kind gentle smile",
    intro: "A gentileza são os pequenos gestos de bondade que alegram o dia de alguém.",
    body: "Ela mora no sorriso oferecido e nas palavras doces.",
    story: "Suave espalhava 'bom dia', 'por favor' e 'obrigado', e o mundo ao redor ficava mais leve.",
    familyActivity: "Façam um desafio de 3 gentilezas por dia e contem ao se reunirem.",
    parentTip: "Reconheça atos gentis do seu filho. Gentileza notada é gentileza repetida.",
    exercise: "Escreva uma gentileza que você pode fazer hoje.",
  },
  {
    id: "perdao",
    label: "Perdão",
    mascotName: "Leve",
    accent: "#60a5fa",
    bg: "#e6f0ff",
    look: "a light-blue dove releasing a small balloon, looking peaceful and relieved",
    intro: "O perdão é soltar a mágoa para que o coração volte a ficar leve.",
    body: "Ele mora no peito que se abre e no abraço que reconcilia.",
    story: "Leve estava magoado, mas ao perdoar o amigo sentiu o coração ficar leve como uma pena.",
    familyActivity: "Pratiquem pedir e oferecer desculpas com sinceridade quando algo der errado.",
    parentTip: "Ensine que perdoar não é concordar com o erro, mas libertar-se do peso.",
    exercise: "Escreva sobre uma vez em que perdoar te deixou mais leve.",
  },
  {
    id: "aceitacao",
    label: "Aceitação",
    mascotName: "Tale",
    accent: "#14b8a6",
    bg: "#d7f6f1",
    look: "a teal turtle smiling calmly, accepting a small mark on its shell as part of it",
    intro: "A aceitação é entender que nem tudo é como queremos, e que tudo bem ser diferente.",
    body: "Ela mora na respiração calma e no coração que entende.",
    story: "Tale tinha uma marquinha no casco e aprendeu a gostar dela, pois fazia parte de quem era.",
    familyActivity: "Falem sobre as diferenças de cada um e por que elas são especiais.",
    parentTip: "Ajude a criança a aceitar limites e diferenças com naturalidade e amor-próprio.",
    exercise: "Escreva algo seu que é diferente e que você aprendeu a gostar.",
  },
  {
    id: "autoestima",
    label: "Autoestima",
    mascotName: "Espe",
    accent: "#f59e0b",
    bg: "#fff1d2",
    look: "a golden lion cub looking in a small mirror with a proud self-loving smile",
    intro: "A autoestima é gostar de quem você é e reconhecer o seu valor.",
    body: "Ela mora no peito que se aceita e no espelho que sorri de volta.",
    story: "Espe olhava no espelho e dizia: 'eu sou especial do meu jeito', e isso o deixava forte.",
    familyActivity: "Cada um diz três coisas de que gosta em si mesmo.",
    parentTip: "Elogie qualidades além da aparência. Autoestima nasce de sentir-se amado e capaz.",
    exercise: "Escreva três coisas que você gosta em você.",
  },
  {
    id: "motivacao",
    label: "Motivação",
    mascotName: "Impulso",
    accent: "#ef4444",
    bg: "#ffe5e1",
    look: "a red cheetah cub ready to dash with sparkly motivated eyes",
    intro: "A motivação é a energia que nos move a começar e continuar algo que queremos.",
    body: "Ela mora na vontade que empurra e no sorriso animado.",
    story: "Impulso acordava com vontade de aprender algo novo e isso o fazia correr atrás dos sonhos.",
    familyActivity: "Criem um lema motivador para repetir antes dos desafios do dia.",
    parentTip: "Conecte tarefas a objetivos que importam para a criança. Sentido gera motivação.",
    exercise: "Escreva algo que te dá vontade de fazer o seu melhor.",
  },
  {
    id: "foco",
    label: "Foco",
    mascotName: "Mira",
    accent: "#2563eb",
    bg: "#e3edff",
    look: "a blue hawk with sharp focused eyes locked onto a single target",
    intro: "O foco é manter a atenção no que importa, sem se deixar levar por distrações.",
    body: "Ele mora no olhar direcionado e na mente firme.",
    story: "Mira mirava seu alvo e ignorava o barulho ao redor, acertando sempre que se concentrava.",
    familyActivity: "Definam um objetivo simples e façam só ele por 5 minutos, sem interrupções.",
    parentTip: "Ensine uma coisa de cada vez. Multitarefa atrapalha o foco em desenvolvimento.",
    exercise: "Escreva uma meta e o que pode te distrair dela.",
  },
  {
    id: "resiliencia",
    label: "Resiliência",
    mascotName: "Bambu",
    accent: "#16a34a",
    bg: "#dcf6e0",
    look: "a green bamboo-sprite bending in the wind without breaking, smiling calmly",
    intro: "A resiliência é a força de se reerguer depois de cair ou de um momento difícil.",
    body: "Ela mora no corpo que se levanta e no coração que continua.",
    story: "Bambu dobrava com o vento forte, mas nunca quebrava, voltando sempre a ficar de pé.",
    familyActivity: "Relembrem um momento difícil que vocês superaram e celebrem essa força.",
    parentTip: "Mostre que dificuldades passam e ensinam. Resiliência cresce com apoio e exemplos.",
    exercise: "Escreva sobre uma vez em que você caiu e se levantou de novo.",
  },
  {
    id: "bondade",
    label: "Bondade",
    mascotName: "Bon",
    accent: "#f59e0b",
    bg: "#fff2d4",
    look: "a golden retriever puppy offering a helping paw with a warm-hearted smile",
    intro: "A bondade é querer o bem das pessoas e agir com o coração.",
    body: "Ela mora nos gestos que ajudam e no sorriso sincero.",
    story: "Bon ajudava sem ser pedido e percebia que a bondade deixava um rastro de sorrisos.",
    familyActivity: "Façam uma 'corrente da bondade': cada gesto bom inspira o próximo.",
    parentTip: "Note e nomeie a bondade do seu filho. O que é reconhecido se fortalece.",
    exercise: "Escreva um ato de bondade que você fez ou viu.",
  },
  {
    id: "solidariedade",
    label: "Solidariedade",
    mascotName: "Juntos",
    accent: "#0d9488",
    bg: "#d7f4f0",
    look: "two teal ants carrying a leaf together, working as a happy team",
    intro: "A solidariedade é se unir para ajudar, porque juntos somos mais fortes.",
    body: "Ela mora nas mãos que se juntam e no 'conte comigo'.",
    story: "Juntos eram formiguinhas que carregavam tudo em equipe, e nada era pesado demais.",
    familyActivity: "Façam uma tarefa em equipe, em que só dá certo se todos ajudarem.",
    parentTip: "Promova atividades cooperativas. Solidariedade se aprende colaborando.",
    exercise: "Escreva uma vez em que ajudar em grupo deu certo.",
  },
]

export const emotionModules: EmotionModule[] = [
  {
    id: "essenciais",
    title: "Módulo 1 · Emoções essenciais",
    description: "As emoções que todo mundo sente e precisa aprender a reconhecer.",
    emotionIds: ["alegria", "tristeza", "medo", "raiva", "nojo", "surpresa"],
  },
  {
    id: "bem-estar",
    title: "Módulo 2 · Bem-estar e alegria",
    description: "Emoções gostosas que enchem o coração de leveza.",
    emotionIds: [
      "calma",
      "gratidao",
      "esperanca",
      "entusiasmo",
      "contentamento",
      "serenidade",
      "otimismo",
      "diversao",
      "empolgacao",
      "satisfacao",
      "alivio",
      "felicidade",
    ],
  },
  {
    id: "medos",
    title: "Módulo 3 · Medos e inseguranças",
    description: "Sentimentos que pedem acolhimento e coragem para enfrentar.",
    emotionIds: [
      "ansiedade",
      "inseguranca",
      "timidez",
      "nervosismo",
      "preocupacao",
      "receio",
      "susto",
      "aflicao",
      "vergonha",
      "constrangimento",
    ],
  },
  {
    id: "raiva-mod",
    title: "Módulo 4 · Raiva e frustração",
    description: "Emoções intensas que ensinam o autocontrole.",
    emotionIds: [
      "frustracao",
      "irritacao",
      "ciume",
      "inveja",
      "impaciencia",
      "teimosia",
      "birra",
      "indignacao",
      "rancor",
      "aborrecimento",
    ],
  },
  {
    id: "afeto",
    title: "Módulo 5 · Conexão e afeto",
    description: "Os sentimentos que aproximam e fortalecem os laços.",
    emotionIds: [
      "carinho",
      "amor",
      "amizade",
      "empatia",
      "compaixao",
      "ternura",
      "saudade",
      "pertencimento",
      "confianca",
      "admiracao",
      "afeto",
      "cuidado",
    ],
  },
  {
    id: "crescimento",
    title: "Módulo 6 · Crescimento e superação",
    description: "Forças internas que ajudam a criança a crescer e brilhar.",
    emotionIds: [
      "coragem",
      "curiosidade",
      "orgulho",
      "determinacao",
      "paciencia",
      "persistencia",
      "criatividade",
      "imaginacao",
      "concentracao",
      "responsabilidade",
      "generosidade",
      "honestidade",
      "respeito",
      "gentileza",
      "perdao",
      "aceitacao",
      "autoestima",
      "motivacao",
      "foco",
      "resiliencia",
      "bondade",
      "solidariedade",
    ],
  },
]

export const emotionById: Record<string, EmotionContent> = Object.fromEntries(
  emotions.map((e) => [e.id, e]),
)

/** Caminho da imagem do mascote de cada emoção */
export function mascotImage(id: string): string {
  return `/mascotes/${id}.png`
}
